### PR TITLE
Support/wagtail 50

### PR DESCRIPTION
**Pull request by katdom13**
## This updates the package for Wagtail 5.0 support.
Support ticket: https://torchbox.monday.com/boards/1124794299/pulses/1131919769

There's no reason the package wouldn't work on versions since 4.1

### CODE REVIEW

**Review by nickmoreton — APPROVED** [review]
Looks good to me.

**Comment by chosak** [comment]
@katdom13 @nickmoreton thanks for this!

Any particular reason you removed support for Wagtail 3.x from the pyproject.toml? It'd be nice to maintain support for 3.x unless there's something about adding 5.x support that requires that.

**Comment by katdom13** [comment]
Hi @chosak ,
I understand that some users may still require support for the EOL TLS version. However, they can choose to use an older version of the package that still supports it.

With that, do we still want to keep the support for 3.x?
Thanks!

**Comment by nickmoreton** [comment]
Hi @chosak I revisited this PR just now to leave Wagtail v3 as a tested version and include the Wagtail v5 version. I also added in Django 4.2 to be tested along with Wagtail v5

Can you please review this and let me know if you see anything you would like to be changed. Thank you.

**Comment by chosak** [comment]
Thank you @katdom13 @nickmoreton! I've merged this in 95fc18e8ef872c778916fee722290d542163750f and will create a new package release shortly.

**Pull request closed without merging**
