### PR TITLE
Add support for wagtail 2.11

### PR DESCRIPTION
**Pull request by m3brown**
Add support for Wagtail 2.11

https://docs.wagtail.io/en/stable/releases/2.11.html

## Removals

- Remove the upper bound for wagtail version in 2.11. This aligns with the recommendation in the [python.org documentation](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires)
  - `It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.`
  - I feel strongly about this change. Without it, each Wagtail update forces me to either disable wagtail-inventory or wait for wagtail-inventory to permit the new version.
- Remove mock from the test stack. Mock is part of the standard library in python 3, and this repo no longer supports python 2. In addition, it doesn't look like any tests are making use of mock.

## Changes

- Update tox and github actions to support 2.11
- Misc: fix linting failure in tests/settings.py

## Testing

1. All existing tests pass

## Notes

-

## Todos

-

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Internet Explorer 8, 9, 10, and 11
- [ ] Edge
- [ ] iOS Safari
- [ ] Chrome for Android

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by Scotchester** [comment]
Hi, Mike :wave: :smile:

**Comment by chosak** [comment]
Nice to get a PR from you, @m3brown!

The reason we pin the upper version is that it's possible that a new version of Wagtail will introduce changes that break this package. Wagtail doesn't strictly follow semantic versioning, so even a minor release bump may remove functionality that wagtail-inventory depends on. For example, in #23 we had to add new code because [Wagtail 2.5 deprecated some pagination helpers](https://docs.wagtail.io/en/latest/releases/2.5.html#changes-to-admin-pagination-helpers). There's definitely a tradeoff and I agree that it's frustrating to have to do a version bump each time there's a new Wagtail release.

The CFPB [development standards](https://github.com/cfpb/development/blob/main/standards/python.md#specifying-dependencies-in-requirementstxt-or-setuppy) currently say that "[o]ur libraries should specify dependencies with supported version ranges ... in setup.py". Perhaps we should loosen or remove this recommendation (ping @willbarton) but if so maybe we should discuss/do that over on the development standards repo first and not as part of this particular upgrade PR.

**Comment by m3brown** [comment]
Thanks for the feedback, @chosak. I understand the alignment with your team standards, and I think it's a case of unfortunate wording.  Some thoughts:
- You can define your supported versions in the README and in the tox config. Of course, this is not programmatically enforced, but that's kind of my point from the perspective of the external community.
- Perhaps your team should consider rephrasing to clarify "unsupported versions" and therefor you can argue that a future version that doesn't exist isn't "unsupported". I realize I'm splitting hairs here.

Perhaps it makes sense for me to roll back the setup.py change and make that its own PR while your team discusses?

**Comment by willbarton** [comment]
> Perhaps it makes sense for me to roll back the setup.py change and make that its own PR while your team discusses?

@m3brown If you could, then we could get this merged. Thanks!

**Comment by m3brown** [comment]
@willbarton updated!

**Comment by m3brown** [comment]
The changes in this PR were resolved by #38

**Pull request closed without merging**
