### PR TITLE
Support Django 4.0.

### PR DESCRIPTION
**Pull request by FlipperPA**
`try` / `except` import for Django URL helper functions. This should fix issues on Django 4+.

### CODE REVIEW

**Comment by chosak** [comment]
@rgs258 @FlipperPA thanks for this, and apologies for the delay in responding.

Since Wagtail 3.0 isn't officially out yet (I believe aiming for next week), there isn't an official Wagtail release that supports Django 4.x yet. So it's a little tricky to support that testing combination without creating a release that specifically targets a pre-release Wagtail version. How have you seen other Wagtail packages handle this?

I've opened #56 which includes this change plus a few other necessary changes to get the tests to pass, including something related to [the module path changes](https://docs.wagtail.org/en/latest/releases/3.0.html#changes-to-module-paths). Would you mind giving that PR a try?

**Comment by FlipperPA** [comment]
Thanks for taking a look @chosak! Django 4.0 support was actually added in Wagtail 2.16: https://docs.wagtail.org/en/latest/releases/2.16.html

**Comment by chosak** [comment]
@FlipperPA of course, my bad! I've retargeted #56 to Wagtail 2.16, and we can add a subsequent PR for 3.0 when it lands.

**Comment by jslay-excella** [comment]
Superseded by #56

**Pull request closed without merging**
