### PR TITLE
to add custom pemissions to the block inventory

### PR DESCRIPTION
**Pull request by hazho**
to prevent non-superusers from seeing the block inventory menu item, I used the (AdminOnlyMenuItem) instead of (MenuItem) to solve #47 issue

### CODE REVIEW

**Comment by chosak** [comment]
Hi @hazho, thanks for filing #47 and for proposing this fix.

Removing block inventory permissions from non-admin users would mean that regular Wagtail users wouldn't be able to audit block usage. I can definitely see a case for being able to restrict access, but a better fix would likely be to add a custom permission for this. This would mean creating a new permission for the inventory data (using [`Meta.permissions`](https://docs.djangoproject.com/en/3.2/ref/models/options/#permissions)), adding [`PermissionRequiredMixin`](https://docs.djangoproject.com/en/3.2/topics/auth/default/#the-permissionrequiredmixin-mixin) to the inventory view, and hiding the menu item based on that permission (example approach [here](https://github.com/cfpb/consumerfinance.gov/blob/3afcc07bbf71950246c9e3b75942860d0793d51d/cfgov/v1/wagtail_hooks.py#L171-L195)).

**Comment by hazho** [comment]
Will Do it soon..!

**Comment by hazho** [comment]
it seems that this path has many turns, it will require time and efforts to track, apply and test the changes

**Comment by hazho** [comment]
I am missing something regarding "register_permissions" hook, it is not registered, even though I followed the documentation

**Comment by chosak** [comment]
This was superseded by #77 which has now been merged - @hazho thank you again for filing this issue and for this PR.

**Pull request closed without merging**
