### PR TITLE
Update helpers.py to detect and correct for row duplication

### PR DESCRIPTION
**Pull request by Pomax**
As per https://github.com/cfpb/wagtail-inventory/issues/43, it is possible to get the DB in a state where there are multiple {page,block} records, causing a crash in `helper.py`'s `create_page_inventory` function.

This PR is current a starting point, to find a good code solution. I personally find this one the best because it both detects _and fixes_ the problem all on its own, but I suspect we'll iterate on this one a bit?

## Additions

I added code that checks for pre-existing rows and _counts_ how many there are, with db pruning if more than one row is found.

## Removals

for now, simply commented off: the original `get_or_create` got "removed" because by design it can't deal with more than one result.

## Changes

-

## Testing

1. I honestly don't know how to test this, short of using `Q()` instructions to intentionally create a corrupt database.

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Internet Explorer 8, 9, 10, and 11
- [ ] Edge
- [ ] iOS Safari
- [ ] Chrome for Android

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by Pomax** [comment]
@chosak looks like all tests pass with the coveralls fix, anything  you'd like me to update codewise?

**Comment by chosak** [comment]
@Pomax would you mind taking a look at #45 as a possible alternate approach, and maybe even trying it out on your database? Re-reading the Django docs [here](https://docs.djangoproject.com/en/dev/ref/models/querysets/#get-or-create) I see mention of how the lack of unique constraint might be the cause of duplicates you're seeing, even though the code is already using `get_or_create`.

**Comment by Pomax** [comment]
I can certainly see what that does, but won't that break when it tries to apply the uniqueness constraint on an already "corrupt" database?

**Comment by Pomax** [comment]
ah, no you have a dedupe migration, nm =P

**Pull request closed without merging**
